### PR TITLE
Fix comment for our own sleep function

### LINKED ISSUE #174: is that actually relevant
https://github.com/lynxthecat/cake-autorate/blob/948003e3dbebd7276933452790f36697466bcda7/cake-autorate_lib.sh#L85
Having had a look at the data, the read version is only slightly faster than the sleep module so from a code hygene and cleanliness perspective I certainly would prefer the module.
However, on OpenWrt that module is made out of unobtainium unless we want to create and maintain a new bash-modules package. So the read versions main convincing argument is that it is:
a) considerable faster than external sleep (has this actually been tested?)
b) does not require to install the non-busybox sleep binary.

So this is mostly a request to change the comment to make it clear that module-sleep is mostly hypothetical and hence not a serious alternative.

### PR DESCRIPTION
**Pull request by rany2**
Closes #174

### CODE REVIEW

File: cake-autorate_lib.sh [hunk 1]
```diff
@@ -12,9 +12,17 @@ exec {__sleep_fd}<> <(:) || true
 
 sleep_s()
 {
-	# calling external sleep binary is slow
-	# bash does have a loadable sleep
-	# but read's timeout can more portably be exploited and this is apparently even faster anyway
+	# Calling the external sleep binary could be rather slow,
+	# especially as we call it very frequently on mediocre hardware.
```
Comment (lynxthecat) [inline cake-autorate_lib.sh:16]:
```suggestion
	# especially as it is called it very frequently and typically on mediocre hardware.
```

File: cake-autorate_lib.sh [hunk 2]
```diff
@@ -12,9 +12,17 @@ exec {__sleep_fd}<> <(:) || true
...
+	#
+	# Due to bash's loadable sleep module not being available,
```
Comment (lynxthecat) [inline cake-autorate_lib.sh:18]:
```suggestion
	# Due to bash's loadable sleep module not being available
```

File: cake-autorate_lib.sh [hunk 3]
```diff
@@ -12,9 +12,17 @@ exec {__sleep_fd}<> <(:) || true
...
+	# on OpenWRT and most embedded systems, we use the bash
+	# read command with a timeout which performs roughly
```
Comment (lynxthecat) [inline cake-autorate_lib.sh:20]:
```suggestion
	# read command with a timeout offers performance that is
```

File: cake-autorate_lib.sh [hunk 4]
```diff
@@ -12,9 +12,17 @@ exec {__sleep_fd}<> <(:) || true
...
+	# as good as bash's sleep module.
```
Comment (lynxthecat) [inline cake-autorate_lib.sh:21]:
```suggestion
	# at least on a par with bash's sleep module.
```

File: cake-autorate_lib.sh [hunk 5]
```diff
@@ -12,9 +12,17 @@ exec {__sleep_fd}<> <(:) || true
 
 sleep_s()
 {
-	# calling external sleep binary is slow
-	# bash does have a loadable sleep
-	# but read's timeout can more portably be exploited and this is apparently even faster anyway
+	# Calling the external sleep binary could be rather slow,
+	# especially as it is called it very frequently and typically on mediocre hardware.
```
Comment (lynxthecat) [inline cake-autorate_lib.sh:16]:
```suggestion
	# especially as it is called very frequently and typically on mediocre hardware.
```

File: cake-autorate_lib.sh [hunk 6]
```diff
@@ -12,9 +12,17 @@ exec {__sleep_fd}<> <(:) || true
...
+	#
+	# Due to bash's loadable sleep module not being available
+	# For OpenWRT and most embedded systems, use of the bash
```
Comment (lynxthecat) [inline cake-autorate_lib.sh:19]:
```suggestion
	# in OpenWRT and most embedded systems, use of the bash
```

File: cake-autorate_lib.sh [hunk 7]
```diff
@@ -12,9 +12,17 @@ exec {__sleep_fd}<> <(:) || true
 
 sleep_s()
 {
-	# calling external sleep binary is slow
-	# bash does have a loadable sleep
-	# but read's timeout can more portably be exploited and this is apparently even faster anyway
+	# Calling the external sleep binary could be rather slow,
+	# especially as it is called very frequently and typically on mediocre hardware.
+	#
+	# Due to bash's loadable sleep module not being available
```
Comment (lynxthecat) [inline cake-autorate_lib.sh:18]:
```suggestion
	# Mindful that bash's loadable sleep module is not typically available
```

File: cake-autorate_lib.sh [hunk 8]
```diff
@@ -12,9 +12,17 @@ exec {__sleep_fd}<> <(:) || true
 
 sleep_s()
 {
-	# calling external sleep binary is slow
-	# bash does have a loadable sleep
-	# but read's timeout can more portably be exploited and this is apparently even faster anyway
+	# Calling the external sleep binary could be rather slow,
+	# especially as it is called very frequently and typically on mediocre hardware.
+	#
+	# Mindful that bash's loadable sleep module is not typically available
```
Comment (lynxthecat) [inline cake-autorate_lib.sh:18]:
```suggestion
	# bash's loadable sleep module is not typically available
```

File: cake-autorate_lib.sh [hunk 9]
```diff
@@ -12,9 +12,17 @@ exec {__sleep_fd}<> <(:) || true
...
+	# in OpenWRT and most embedded systems, use of the bash
```
Comment (lynxthecat) [inline cake-autorate_lib.sh:19]:
```suggestion
	# in OpenWRT and most embedded systems, and use of the bash
```
